server:
  port: 8081
spring:
  application:
    name: plat-test
  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: nacos-local.zongsheng.tech:80 # Nacos 服务器地址

  # Zipkin 配置项，对应 ZipkinProperties 类
  zipkin:
    base-url: http://localhost:9411 # Zipkin 服务的地址

# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    base-packages: com.zongs365.plat.test # 指定 Dubbo 服务实现类的扫描基准包
  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
  protocols:
    dubbo:
      name: dubbo # 协议名称
      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    address: spring-cloud://nacos-local.zongsheng.tech:80 # 指定 Dubbo 服务注册中心的地址
  # Dubbo 服务提供者的配置，对应 ProviderConfig 类
  provider:
    filter: tracing,logRpcFilter
  consumer:
    filter: tracing
    timeout: 16000
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: 'center-test,center-diboot' # 设置订阅的应用列表，默认为 * 订阅所有应用

